create table t_member (
    member_no  int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null,
    login_id   varchar(500)  not null,
    login_pw   varchar(1000) not null,
--    reg_id     varchar(500),
--    reg_dt     NOW(),
--    reg_ip     varchar(500)
    primary key (member_no)
);